- label: "Start here"
  link: "/"
- label: "Plugins"
  items:
  - label: "ğŸ““ Pyroam"
    link: "pyroam/"
  - label: "ğŸ—ƒï¸ roam/sr"
    link: "roamsr/"
  - label: "ğŸ¾ LittleScripts"
    link: "littlescripts/"
